---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - op4apigroup.op4domain
  resources:
  - op4apikinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - op4apigroup.op4domain
  resources:
  - op4apikinds/finalizers
  verbs:
  - update
- apiGroups:
  - op4apigroup.op4domain
  resources:
  - op4apikinds/status
  verbs:
  - get
  - patch
  - update
